главная страница 1.0
htmlacademy-adaptive/309701-cat-energy-22 pull request #3
Opened 2021-03-26 19:55 UTC by akoross

2021-03-26 20:58 UTC, baileys-li requested changes

2021-03-26 20:58 UTC, baileys-li commented on source/index.html
> +        <button class="promo-button button">подобрать программу</button>
Это ссылка на страницу с формой

2021-03-26 20:58 UTC, baileys-li commented on source/index.html
> +        <img class="page-header__logo" src="./img/logo-title.svg" alt="Cat Energy Питание для котов">
Не хватает картинки с маскотом (иконка с котом. Ну и структура тогда будет что-то вроде:
```
.page-header__logo
        img.page-header__logo-mascot
        img.page-header__logo-text
```

2021-03-26 20:58 UTC, baileys-li commented on source/index.html
> +        <button class="promo-button button">подобрать программу</button>
Я не совсем понимаю зачем их выделять в отдельные блоки, а не 
```
h1.promo__title
p.promo__subtitle
button.promo__button
```

Это не ошибка, но странно

2021-03-26 20:58 UTC, baileys-li commented on source/index.html
> +        </dl>
Лист определений тут семантически спорный. Плюс с такой структурой вызовет ошибки валидации

2021-03-26 20:58 UTC, baileys-li commented on source/index.html
> +        <button class="promo-button button">подобрать программу</button>
Не хватает картинки с банкой. Она контентной изображение

2021-03-26 20:58 UTC, baileys-li commented on source/index.html
> +              <img src="./img/icon_leaf.svg" alt="Иконка">
Хотелось бы более осмысленных альтов. 
Ну и размеры иконок не помешали бы в вёрстке. Поможет браузеру заранее отрисовывать слоты под картинки. А потом вообще будет необходимо.

2021-03-26 20:58 UTC, baileys-li commented on source/index.html
> +            <img src="./img/cat_slim.png" alt="Похудение" class="selection__item-icon">
Там пантеры вполне себе векторные. Лучше воспользоваться этим, потому что растр потом будет адаптировать сложнее

2021-03-26 20:58 UTC, baileys-li commented on source/index.html
> +          <div class="example__result-item">
**[Необязательно]** Можно подобрать более семантические теги, чем div

2021-03-26 20:58 UTC, baileys-li commented on source/index.html
> +              <div class="example__before"></div>
Я подозреваю, ты где-то подсмотрел, что подобный слайдер был сделан с фоновыми изображениями.
Я против. Коты «До»/«После» — это очевидно контентные  картинки и должны быть в вёрстке

2021-03-26 20:58 UTC, baileys-li commented on source/index.html
> +      <div class="wrapper contacts__wraper">
**[Необязательно]** <address> более семантичен

2021-03-26 20:58 UTC, baileys-li commented on source/index.html
> +          <a href="vkontakte.ru" class="social__link vk"></a>
Вставь иконки соц сетей с альтами

2021-03-26 21:46 UTC, akoross commented on source/index.html
> +        <img class="page-header__logo" src="./img/logo-title.svg" alt="Cat Energy Питание для котов">
я картинку не добавлял, поскольку она различна на разных экранах, планировал добавить ее: before, или такой вариант плох?

2021-03-27 09:29 UTC, baileys-li commented on source/index.html
> +        <img class="page-header__logo" src="./img/logo-title.svg" alt="Cat Energy Питание для котов">
`:before` не подходит. Айдентика это часть контента и её стоит вынести в вёрстку, чтобы браузер отдавал ей предпочтение

Мы в чате наставников ещё спорим, как лучше реализовать переходы между экранами, но сейчас я хочу чтобы был хотя бы мобильный маскот в вёрстке. 
А то что она разная вообще ничего страшного. Вас в следующих лекциях научат адаптивить картинки.

2021-03-27 11:28 UTC, merged